{
    "config": {
        "error": {
            "cannot_connect": "Nepoda\u0159ilo se p\u0159ipojit",
            "invalid_auth": "Neplatn\u00e9 ov\u011b\u0159en\u00ed",
            "unknown": "Neo\u010dek\u00e1van\u00e1 chyba"
        },
        "step": {
            "auth": {
                "data": {
                    "password": "Heslo",
                    "username": "U\u017eivatelsk\u00e9 jm\u00e9no"
                },
                "description": "Za\u0159\u00edzen\u00ed IoTawatt vy\u017eaduje ov\u011b\u0159en\u00ed. Zadejte u\u017eivatelsk\u00e9 jm\u00e9no a heslo a klepn\u011bte na tla\u010d\u00edtko Odeslat."
            },
            "user": {
                "data": {
                    "host": "Hostitel"
                },
                "data_description": {
                    "host": "N\u00e1zev hostitele nebo IP adresa va\u0161eho za\u0159\u00edzen\u00ed IoTaWatt."
                }
            }
        }
    }
}