{
    "config": {
        "error": {
            "cannot_connect": "No se pudo conectar",
            "invalid_auth": "Autenticaci\u00f3n no v\u00e1lida",
            "unknown": "Error inesperado"
        },
        "step": {
            "auth": {
                "data": {
                    "password": "Contrase\u00f1a",
                    "username": "Nombre de usuario"
                },
                "description": "El dispositivo IoTawatt requiere autenticaci\u00f3n. Por favor, introduce el nombre de usuario y la contrase\u00f1a y selecciona el bot\u00f3n Enviar."
            },
            "user": {
                "data": {
                    "host": "Host"
                },
                "data_description": {
                    "host": "El nombre de host o la direcci\u00f3n IP de tu dispositivo IoTaWatt."
                }
            }
        }
    }
}