{
    "config": {
        "error": {
            "cannot_connect": "Falha ao conectar",
            "invalid_auth": "Autentica\u00e7\u00e3o inv\u00e1lida",
            "unknown": "Erro inesperado"
        },
        "step": {
            "auth": {
                "data": {
                    "password": "Senha",
                    "username": "Usu\u00e1rio"
                }
            },
            "user": {
                "data": {
                    "host": "Host"
                },
                "data_description": {
                    "host": "O nome do host ou endere\u00e7o IP do seu dispositivo IoTaWatt."
                }
            }
        }
    }
}