{
    "config": {
        "abort": {
            "already_configured": "A szolg\u00e1ltat\u00e1s m\u00e1r konfigur\u00e1lva van"
        },
        "error": {
            "not_allowed_dir": "A konfigur\u00e1lt el\u00e9r\u00e9si \u00fat nem szerepel az enged\u00e9lyez\u00e9si list\u00e1ban",
            "not_dir": "A konfigur\u00e1lt el\u00e9r\u00e9si \u00fat nem k\u00f6nyvt\u00e1r",
            "not_readable_dir": "A konfigur\u00e1lt el\u00e9r\u00e9si \u00fat nem olvashat\u00f3"
        },
        "step": {
            "user": {
                "data": {
                    "folder": "A figyelt mappa el\u00e9r\u00e9si \u00fatja",
                    "patterns": "Figyelend\u0151 mint\u00e1(k)"
                },
                "data_description": {
                    "folder": "Az \u00fatvonalnak gy\u00f6k\u00e9rt\u0151l kell indulnia, p\u00e9ld\u00e1ul `/config`",
                    "patterns": "P\u00e9lda: `*.yaml` csak a yaml f\u00e1jlok megtekint\u00e9s\u00e9hez"
                }
            }
        }
    },
    "entity": {
        "sensor": {
            "folder_watcher": {
                "state_attributes": {
                    "dest_file": {
                        "name": "C\u00e9l f\u00e1jl"
                    },
                    "dest_folder": {
                        "name": "C\u00e9l mappa"
                    },
                    "dest_path": {
                        "name": "C\u00e9l \u00fatvonal"
                    },
                    "event_type": {
                        "name": "Esem\u00e9ny t\u00edpus"
                    },
                    "file": {
                        "name": "F\u00e1jl"
                    },
                    "folder": {
                        "name": "Mappa"
                    },
                    "path": {
                        "name": "\u00datvonal"
                    }
                }
            }
        }
    },
    "issues": {
        "import_failed_not_allowed_path": {
            "description": "A Mappafigyel\u0151 YAML haszn\u00e1lat\u00e1val t\u00f6rt\u00e9n\u0151 konfigur\u00e1l\u00e1sa elt\u00e1vol\u00edt\u00e1sra ker\u00fcl, de a konfigur\u00e1ci\u00f3j\u00e1t nem lehetett import\u00e1lni, mivel a {path} mappa nem szerepel a konfigur\u00e1lt enged\u00e9lyez\u00e9si list\u00e1ban.\n\nAdja hozz\u00e1 a config.yaml ` {config_variable} ` r\u00e9sz\u00e9hez \u00e9s ind\u00edtsa \u00fajra a Home Assistant alkalmaz\u00e1st az import\u00e1l\u00e1shoz \u00e9s a probl\u00e9ma megold\u00e1s\u00e1hoz.",
            "title": "A Mappafigyel\u0151 YAML-konfigur\u00e1ci\u00f3ja nem import\u00e1lhat\u00f3"
        },
        "setup_not_allowed_path": {
            "description": "A(z) {path} \u00fatvonal nem el\u00e9rhet\u0151 vagy nem enged\u00e9lyezett a hozz\u00e1f\u00e9r\u00e9s.\n\nK\u00e9rem, ellen\u0151rizze, hogy az \u00fatvonal el\u00e9rhet\u0151-e, \u00e9s adja hozz\u00e1 a `{config_variable}` \u00e9rt\u00e9k\u00e9t a config.yaml f\u00e1jlban, majd ind\u00edtsa \u00fajra a Home Assistantot a probl\u00e9ma megold\u00e1sa \u00e9rdek\u00e9ben.",
            "title": "A(z) {path} mappafigyel\u0151 konfigur\u00e1ci\u00f3ja nem ind\u00edthat\u00f3 el"
        }
    },
    "options": {
        "step": {
            "init": {
                "data": {
                    "patterns": "Figyelend\u0151 mint\u00e1(k)"
                },
                "data_description": {
                    "patterns": "P\u00e9lda: `*.yaml` csak a yaml f\u00e1jlok megtekint\u00e9s\u00e9hez"
                }
            }
        }
    }
}