{
    "config": {
        "abort": {
            "already_configured": "L'appareil est d\u00e9j\u00e0 configur\u00e9",
            "reauth_successful": "La r\u00e9-authentification a r\u00e9ussi",
            "reconfigure_successful": "La reconfiguration a r\u00e9ussi"
        },
        "error": {
            "cannot_connect": "\u00c9chec de connexion",
            "invalid_auth": "Authentification non valide",
            "unknown": "Erreur inattendue"
        },
        "step": {
            "reauth_confirm": {
                "data": {
                    "password": "Mot de passe",
                    "username": "Nom d'utilisateur"
                },
                "title": "L'authentification a expir\u00e9 pour {name}"
            },
            "reconfigure_confirm": {
                "data": {
                    "host": "H\u00f4te",
                    "password": "Mot de passe",
                    "port": "Port",
                    "ssl": "Utilise un certificat SSL",
                    "username": "Nom d'utilisateur",
                    "verify_ssl": "V\u00e9rifier le certificat SSL"
                },
                "data_description": {
                    "host": "Le nom d'h\u00f4te ou l'adresse IP de l'appareil ex\u00e9cutant votre instance pyLoad.",
                    "port": "pyLoad utilise le port 8000 par d\u00e9faut."
                }
            },
            "user": {
                "data": {
                    "host": "H\u00f4te",
                    "name": "Nom",
                    "password": "Mot de passe",
                    "port": "Port",
                    "ssl": "Utilise un certificat SSL",
                    "username": "Nom d'utilisateur",
                    "verify_ssl": "V\u00e9rifier le certificat SSL"
                },
                "data_description": {
                    "host": "Le nom d'h\u00f4te ou l'adresse IP de l'appareil ex\u00e9cutant votre instance pyLoad.",
                    "name": "Le nom \u00e0 utiliser pour votre instance pyLoad dans Home Assistant",
                    "port": "pyLoad utilise le port 8000 par d\u00e9faut."
                }
            }
        }
    },
    "entity": {
        "button": {
            "abort_downloads": {
                "name": "Abandonner tous les t\u00e9l\u00e9chargements en cours"
            },
            "delete_finished": {
                "name": "Supprimer les fichiers/packages termin\u00e9s"
            },
            "restart": {
                "name": "Red\u00e9marrer pyload core"
            },
            "restart_failed": {
                "name": "Red\u00e9marrez tous les fichiers ayant \u00e9chou\u00e9"
            }
        },
        "sensor": {
            "active": {
                "name": "T\u00e9l\u00e9chargements actifs"
            },
            "free_space": {
                "name": "Espace libre"
            },
            "queue": {
                "name": "T\u00e9l\u00e9chargements en attente"
            },
            "speed": {
                "name": "Vitesse"
            },
            "total": {
                "name": "Total des t\u00e9l\u00e9chargements"
            }
        },
        "switch": {
            "download": {
                "name": "Suspendre/Reprendre la file d\u2019attente"
            },
            "reconnect": {
                "name": "Reconnexion automatique"
            }
        }
    },
    "exceptions": {
        "service_call_auth_exception": {
            "message": "Impossible d'envoyer la commande \u00e0 pyLoad en raison d'une erreur d'authentification, r\u00e9essayez plus tard"
        },
        "service_call_exception": {
            "message": "Impossible d'envoyer la commande \u00e0 pyLoad en raison d'une erreur de connexion, r\u00e9essayez plus tard"
        },
        "setup_authentication_exception": {
            "message": "\u00c9chec de l'authentification pour {username}, v\u00e9rifiez vos informations de connexion"
        },
        "setup_parse_exception": {
            "message": "Impossible d'analyser les donn\u00e9es de l'API pyLoad, r\u00e9essayez plus tard"
        },
        "setup_request_exception": {
            "message": "Impossible de se connecter et de r\u00e9cup\u00e9rer les donn\u00e9es de l'API pyLoad, r\u00e9essayez plus tard"
        }
    },
    "issues": {
        "deprecated_yaml_import_issue_cannot_connect": {
            "description": "La configuration de pyLoad \u00e0 l'aide de YAML est en cours de suppression, mais une erreur de connexion s'est produite lors de la tentative d'importation de la configuration YAML. \n\nVeuillez v\u00e9rifier que vous disposez d'une connexion Internet stable et red\u00e9marrer Home Assistant pour r\u00e9essayer ou supprimer la configuration pyLoad YAML de votre fichier configuration.yaml et continuer \u00e0 [configurer l'int\u00e9gration]({url}) manuellement.",
            "title": "L'importation de la configuration pyLoad en YAML a \u00e9chou\u00e9"
        },
        "deprecated_yaml_import_issue_invalid_auth": {
            "description": "La configuration de pyLoad \u00e0 l'aide de YAML est en cours de suppression, mais une erreur d'authentification s'est produite lors de la tentative d'importation de la configuration YAML.\n\nCorrigez la configuration YAML et red\u00e9marrez Home Assistant pour r\u00e9essayer ou supprimez la configuration pyLoad YAML de votre fichier configuration.yaml et continuez \u00e0 [configurer l'int\u00e9gration]({url}) manuellement.",
            "title": "L'importation de la configuration pyLoad en YAML a \u00e9chou\u00e9"
        },
        "deprecated_yaml_import_issue_unknown": {
            "description": "La configuration de pyLoad \u00e0 l'aide de YAML est en cours de suppression, mais une erreur inconnue s'est produite lors de la tentative d'importation de la configuration YAML.\n\nAssurez-vous que la configuration YAML est correcte et red\u00e9marrez Home Assistant pour r\u00e9essayer ou supprimez la configuration pyLoad YAML de votre fichier configuration.yaml et continuez \u00e0 [configurer l'int\u00e9gration]({url}) manuellement.",
            "title": "L'importation de la configuration pyLoad en YAML a \u00e9chou\u00e9"
        }
    }
}