{
    "config": {
        "abort": {
            "already_configured": "Ger\u00e4t ist bereits konfiguriert",
            "reauth_failed_existing": "Der Konfigurationseintrag konnte nicht aktualisiert werden. Bitte entferne die Integration und richte sie erneut ein.",
            "reauth_successful": "Die erneute Authentifizierung war erfolgreich",
            "unknown": "Unerwarteter Fehler"
        },
        "error": {
            "cannot_connect": "Verbindung fehlgeschlagen",
            "invalid_api_key": "Ung\u00fcltiger API-Schl\u00fcssel",
            "not_main_key": "Falscher API-Schl\u00fcsseltyp erkannt, verwende den API-Hauptschl\u00fcssel",
            "reauth_failed_matching_account": "Der von dir angegebene API-Schl\u00fcssel stimmt nicht mit der Konto-ID f\u00fcr die vorhandene Konfiguration \u00fcberein.",
            "unknown": "Unerwarteter Fehler"
        },
        "step": {
            "reauth_confirm": {
                "data": {
                    "api_key": "API-Schl\u00fcssel"
                },
                "description": "Du musst einen neuen Haupt-API-Schl\u00fcssel von UptimeRobot bereitstellen",
                "title": "Die Authentifizierung ist abgelaufen f\u00fcr {name}"
            },
            "user": {
                "data": {
                    "api_key": "API-Schl\u00fcssel"
                },
                "description": "Du musst den Haupt-API-Schl\u00fcssel von UptimeRobot bereitstellen"
            }
        }
    },
    "entity": {
        "sensor": {
            "monitor_status": {
                "state": {
                    "down": "Offline",
                    "not_checked_yet": "Noch nicht gepr\u00fcft",
                    "pause": "Pause",
                    "seems_down": "Scheint offline zu sein",
                    "up": "Online"
                }
            }
        }
    }
}