{
    "config": {
        "abort": {
            "already_configured": "Le compte est d\u00e9j\u00e0 configur\u00e9",
            "reauth_failed_existing": "Impossible de mettre \u00e0 jour l'entr\u00e9e de configuration, veuillez supprimer l'int\u00e9gration et la configurer \u00e0 nouveau.",
            "reauth_successful": "La r\u00e9-authentification a r\u00e9ussi",
            "unknown": "Erreur inattendue"
        },
        "error": {
            "cannot_connect": "\u00c9chec de connexion",
            "invalid_api_key": "Cl\u00e9 d'API non valide",
            "not_main_key": "Mauvais type de cl\u00e9 d'API d\u00e9tect\u00e9, utilisez la cl\u00e9 d'API \u00ab\u00a0principale\u00a0\u00bb",
            "reauth_failed_matching_account": "La cl\u00e9 API que vous avez fournie ne correspond pas \u00e0 l\u2019ID de compte pour la configuration existante.",
            "unknown": "Erreur inattendue"
        },
        "step": {
            "reauth_confirm": {
                "data": {
                    "api_key": "Cl\u00e9 d'API"
                },
                "description": "Vous devez fournir une nouvelle cl\u00e9 d'API \u00ab\u00a0principale\u00a0\u00bb \u00e0 partir d'UptimeRobot",
                "title": "L'authentification a expir\u00e9 pour {name}"
            },
            "user": {
                "data": {
                    "api_key": "Cl\u00e9 d'API"
                },
                "description": "Vous devez fournir la cl\u00e9 d'API \u00ab\u00a0principale\u00a0\u00bb \u00e0 partir d'UptimeRobot"
            }
        }
    },
    "entity": {
        "sensor": {
            "monitor_status": {
                "state": {
                    "pause": "Mettre en pause"
                }
            }
        }
    }
}