{
    "config": {
        "error": {
            "cannot_connect": "Sikertelen csatlakoz\u00e1s",
            "invalid_auth": "Enged\u00e9lyezze a hiteles\u00edt\u00e9st a m\u00fctesync be\u00e1ll\u00edt\u00e1sai > Hiteles\u00edt\u00e9s men\u00fcpontban",
            "unknown": "V\u00e1ratlan hiba"
        },
        "step": {
            "user": {
                "data": {
                    "host": "Hoszt"
                },
                "data_description": {
                    "host": "A mutesync-eszk\u00f6z g\u00e9pneve vagy IP-c\u00edme."
                }
            }
        }
    },
    "entity": {
        "binary_sensor": {
            "in_meeting": {
                "name": "\u00c9rtekezleten"
            },
            "muted": {
                "name": "N\u00e9m\u00edtva"
            }
        }
    }
}